//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPower.QnA.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRS_Knowledge
    {
        public string FRS_KnowledgeType { get; set; }
        public string RecId { get; set; }
        public Nullable<System.DateTime> LastModDateTime { get; set; }
        public string LastModBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string OwnerType { get; set; }
        public string Owner_Valid { get; set; }
        public string OwnerTeam { get; set; }
        public string OwnerTeam_Valid { get; set; }
        public string Author { get; set; }
        public string Author_Valid { get; set; }
        public string Collection { get; set; }
        public string Collection_Valid { get; set; }
        public Nullable<int> CountFeedback { get; set; }
        public Nullable<int> CountHelpful { get; set; }
        public Nullable<int> CountNotHelpful { get; set; }
        public Nullable<int> CountView { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string Environment { get; set; }
        public string Environment_Valid { get; set; }
        public string Keywords { get; set; }
        public Nullable<System.DateTime> NextReviewDate { get; set; }
        public string OwnerEmail { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<System.DateTime> RetiredDate { get; set; }
        public string Status { get; set; }
        public string Status_Valid { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> UserRating { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<bool> IsBusinessApprovalRequired { get; set; }
        public Nullable<bool> IsPresentationApprovalRequired { get; set; }
        public Nullable<bool> IsTechnicalApprovalRequired { get; set; }
        public Nullable<int> KnowledgeNumber { get; set; }
        public Nullable<short> KnowledgeVersion { get; set; }
        public string DisplayText { get; set; }
        public byte[] AttachmentData { get; set; }
        public string AttachmentData_FileType { get; set; }
        public string AttachmentData_FileName { get; set; }
        public string Category { get; set; }
        public string Category_Valid { get; set; }
        public string Subcategory { get; set; }
        public string Subcategory_Valid { get; set; }
        public Nullable<bool> ReadOnly { get; set; }
        public string Owner { get; set; }
        public string SocialTextHeader { get; set; }
        public string Details { get; set; }
        public string Resolution { get; set; }
        public string OwnerFullName { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<System.DateTime> TodaysDate { get; set; }
    }
}
